"""add callback_processed_at to payments

Revision ID: 62bd012bd3aa
Revises: 30df08f0de7e
Create Date: 2025-11-14 17:38:46.937353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62bd012bd3aa'
down_revision: Union[str, Sequence[str], None] = '30df08f0de7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('callback_processed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'callback_processed_at')
    # ### end Alembic commands ###
